export type Quote = { text: string; author: string };

export const QUOTES: Quote[] = [
  { text: 'Uma sala sem livros é como um corpo sem alma.', author: 'Cícero' },
  { text: 'Um livro é um sonho que você segura na mão.', author: 'Neil Gaiman' },
  { text: 'Ler é viajar sem sair do lugar.', author: 'Anônimo' },
  { text: 'Os livros são abelhas que levam o pólen de uma inteligência a outra.', author: 'James Russell Lowell' },
  { text: 'Um leitor vive mil vidas antes de morrer. O homem que nunca lê vive apenas uma.', author: 'George R. R. Martin' },
  { text: 'Livros não mudam o mundo. As pessoas mudam o mundo. Os livros só mudam as pessoas.', author: 'Mário Quintana' },
  { text: 'A leitura é uma fonte inesgotável de prazer.', author: 'Monteiro Lobato' },
  { text: 'Quem lê viaja, quem viaja descobre, quem descobre vive.', author: 'Anônimo' },
  { text: 'Um livro é um amigo que nunca trai.', author: 'Voltaire' },
  { text: 'A leitura é para o espírito o que o exercício é para o corpo.', author: 'Joseph Addison' },
  { text: 'Não existe melhor amigo do que um livro.', author: 'Ernest Hemingway' },
  { text: 'A casa onde os livros não têm honra é triste, vazia, mesmo cheia de móveis.', author: 'Mário Quintana' },
  { text: 'Livros são espelhos: você só vê neles o que já tem dentro de si.', author: 'Carlos Ruiz Zafón' },
  { text: 'Um livro deve ser o machado que quebra o mar de gelo dentro de nós.', author: 'Franz Kafka' },
  { text: 'Sem livros, a história é silenciosa, a literatura muda, a ciência paralisada.', author: 'Barbara Tuchman' },
  { text: 'A leitura engrandece a alma.', author: 'Voltaire' },
  { text: 'Um leitor não percebe que está sozinho. Ele se sente acompanhado.', author: 'Carlos Drummond de Andrade' },
  { text: 'O livro é um mestre que fala ao espírito sem nos cansar.', author: 'Marcel Proust' },
  { text: 'A maior das felicidades para quem lê é descobrir um livro novo de seu autor preferido.', author: 'Italo Calvino' },
  { text: 'Quem não lê, não escreve, e quem não escreve, não pensa.', author: 'Carlos Heitor Cony' },
  { text: 'Cada leitor, ao ler, lê a si mesmo.', author: 'Marcel Proust' },
  { text: 'Os livros nos dão um deleite que vai até o fundo do coração.', author: 'Petrarca' },
  { text: 'Há crimes piores do que queimar livros. Um deles é não lê-los.', author: 'Joseph Brodsky' },
  { text: 'Livros são portas que se abrem para outros mundos.', author: 'Cecília Meireles' },
  { text: 'Aprender a ler é a coisa mais importante que me aconteceu.', author: 'Mario Vargas Llosa' },
  { text: 'Os livros são os mais silenciosos e constantes amigos.', author: 'Charles Eliot' },
  { text: 'Um quarto sem livros é como um corpo sem alma.', author: 'G. K. Chesterton' },
  { text: 'Um bom livro é aquele que se abre com expectativa e se fecha com proveito.', author: 'Amos Bronson Alcott' },
  { text: 'A leitura traz ao homem plenitude, o discurso segurança e a escrita precisão.', author: 'Francis Bacon' },
  { text: 'Livros são amigos que nunca decepcionam.', author: 'Thomas Carlyle' },
  { text: 'Não há tristeza que um livro não possa minorar.', author: 'Charles de Montesquieu' },
  { text: 'Se quiseres ser universal, fala da tua aldeia.', author: 'Liev Tolstói' },
  { text: 'A leitura é uma conversa com os homens mais ilustres dos séculos passados.', author: 'René Descartes' },
  { text: 'O homem culto é aquele que não conhece todos os livros, mas que conhece algumas verdades.', author: 'Marcus Aurelius' },
  { text: 'A literatura é a forma mais agradável de ignorar a vida.', author: 'Fernando Pessoa' },
  { text: 'Tudo o que sou hoje devo aos livros que li.', author: 'Theodore Roosevelt' },
  { text: 'Quem ousa ensinar, nunca deve parar de aprender.', author: 'John Cotton Dana' },
  { text: 'A leitura é a viagem dos que não podem tomar o trem.', author: 'Francis de Croisset' },
  { text: 'Estudar não é um ato de consumir ideias, mas de criá-las e recriá-las.', author: 'Paulo Freire' },
  { text: 'Um homem com um livro nunca está sozinho.', author: 'Provérbio inglês' },
  { text: 'Quem lê viaja sem precisar fazer as malas.', author: 'Anônimo' },
  { text: 'Não existe homem mais culto do que aquele que escolhe bem o que vai ler.', author: 'Marquês de Maricá' },
  { text: 'Vivendo, se aprende; mas o que se aprende, mais, é só a fazer outras maiores perguntas.', author: 'Guimarães Rosa' },
  { text: 'Os livros me ensinaram a pensar e o pensamento me fez livre.', author: 'Ricardo León' },
  { text: 'Os livros são os portadores da civilização.', author: 'Barbara Tuchman' },
  { text: 'Toda biblioteca tem alma.', author: 'Carlos Ruiz Zafón' },
  { text: 'Ler é beber e comer. O espírito que não lê emagrece como o corpo que não come.', author: 'Victor Hugo' },
  { text: 'Conhece-te a ti mesmo.', author: 'Sócrates' },
  { text: 'O que vale na vida não é o ponto de partida e sim a caminhada.', author: 'Cora Coralina' },
  { text: 'A vida é breve, a arte é longa.', author: 'Hipócrates' },
  { text: 'Os livros me salvaram do silêncio.', author: 'Anatole France' },
  { text: 'Aquilo que se enraíza profundamente em nossa essência foi adquirido nos livros.', author: 'Jorge Luis Borges' },
  { text: 'Quem não lê livros é como uma árvore sem raízes.', author: 'Provérbio chinês' },
  { text: 'Cuidado com o homem de um só livro.', author: 'São Tomás de Aquino' },
  { text: 'Quando eu tenho um pouco de dinheiro, compro livros; e se sobra algum, compro comida e roupas.', author: 'Erasmo de Roterdã' },
  { text: 'A pessoa que não lê vive apenas uma vida. A que lê vive cinco mil.', author: 'Umberto Eco' },
  { text: 'Quem lê um livro lê duas coisas: as palavras e si mesmo.', author: 'Mario Quintana' },
  { text: 'Há livros que devemos saborear, outros devorar, e poucos mastigar e digerir.', author: 'Francis Bacon' },
  { text: 'Para mim, um livro é uma transformação.', author: 'Jorge Luis Borges' },
  { text: 'Não basta ter belos livros; é preciso lê-los.', author: 'Ronsard' },
  { text: 'Um livro lido cem vezes torna-se mil livros diferentes.', author: 'Provérbio chinês' },
  { text: 'Se os livros não fossem o melhor do mundo, Deus não os teria deixado conosco.', author: 'Walt Whitman' },
  { text: 'O livro é a melhor obra criada pelo homem.', author: 'Voltaire' },
  { text: 'A leitura nos ajuda a saber quem somos.', author: 'Christine Nöstlinger' },
  { text: 'O livro é prova de que os homens são capazes de fazer magia.', author: 'Carl Sagan' },
  { text: 'Cada livro fechado tem o seu silêncio próprio.', author: 'Cecília Meireles' },
  { text: 'Os bons livros são como bons amigos, poucos e selecionados.', author: 'Louisa May Alcott' },
  { text: 'O livro torna o homem mais humano.', author: 'Plínio, o Velho' },
  { text: 'Quanto maior o número de livros, maior o número de mundos para se descobrir.', author: 'Anônimo' },
  { text: 'Os livros nos abrem para o universo.', author: 'Olavo Bilac' },
];

export function getQuoteOfTheDay(): Quote {
  const start = new Date(new Date().getFullYear(), 0, 0);
  const diff = Date.now() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return QUOTES[dayOfYear % QUOTES.length];
}